- hosts: docker_host
  gather_facts: no

  tasks:
    - docker_container:
        name: java-hello-world
        image: ttoii/java-hello-world
        state: started
        recreate: yes
        ports:
          - "8080:8080"
