- name: Docker Image Build
  hosts: ansible_host
  gather_facts: false

  tasks:
    - command: docker image build -t ttoii/java-hello-world java-hello-world/
    - command: docker login -u ttoii -p "{{ lookup('env', 'PASS') }}"
    - command: docker push ttoii/java-hello-world
    - command: docker logout

- name: Docker Run
  hosts: docker_host
  gather_facts: false  

  tasks:
    - command: docker container rm -f java-hello-world
      ignore_errors: yes
    - command: docker container run -d -p 8080:8080 --name java-hello-world ttoii/java-hello-world

