- hosts: ansible_host
  gather_facts: no

  tasks:
    - name: Login to Docker Hub
      docker_login:
        username: ttoii
        password: "{{ lookup('env', 'PASS' }}"
        reauthorize: yes

    - name: Build and Push Image
      docker_image:
        build:
          path: /home/vagrant/java-hello-world
        name: ttoii/java-hello-world
        push: yes
        source: build
