apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello
spec:
  replicas: 3
  selector:
    mathchLabels:
      app: java-hello
  template:
    metadata:
      labels:
        app: java-hello
      spec:
        containers:
          - name: java-hello
            image: ttoii/java-hello-world
            ports:
              - containerPort: 8080
